server {
    listen 80;
    server_name your-server-ip;
    location /.well-known/acme-challenge/ {
        root /var/www/acme;
    }
    location / {
        return 308 https://your-server-ip$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name your-server-ip;
    ssl_certificate /etc/nginx/ssl/interview/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/interview/key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:InterviewTLS:10m;
    ssl_session_timeout 1d;
    client_max_body_size 600k;

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://127.0.0.1:8787;
        proxy_read_timeout 30s;
    }
}
